# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'rules/recording_rules.yml'
  - 'rules/alerting_rules.yml'

scrape_configs:
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'agent-backend'
    metrics_path: '/agent_backend/metrics' 
    static_configs:
      - targets: ['kong:8000']

  - job_name: 'user-profile-service'
    metrics_path: '/user_profile/metrics' 
    static_configs:
      - targets: ['kong:8000']
      
  - job_name: 'post-service'
    metrics_path: '/post/metrics' 
    static_configs:
      - targets: ['kong:8000']
      
  - job_name: 'post-comment-service'
    metrics_path: '/post_comment/metrics' 
    static_configs:
      - targets: ['kong:8000']

  - job_name: 'image-service'
    metrics_path: '/image_service/metrics' 
    static_configs:
      - targets: ['kong:8000']


  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
 
  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    
  - job_name: 'kong_prometheus'
    static_configs:
      - targets: ['kong:8001']
    